language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: DSAoC2saAhoIJKz396W9ZBvmZBTw/Z06zN8yuedCIzFs1WTB4qYC5m4eYdEsemh86zq2X6nuUt4mtiRCmx+00O4HRbsCoXOxXZPR46xx/jDiLi6nLMObe4a8Z7kSVtwwQDTfjnplcTUqVWUy7Nv+uvyJTavGqLGP68flBtMLJKPqwNFyJTGGh2XTvPcstZOxW/QC8yd2kXnT/Qb6Yju5waS+rFDRXMAT3HB9o90kS/MGsz360wq3TI0w/7yr6MbGjXJx+Wr9N6zXfCIXr8EH1nE0ug56cNWluJ8hVvwhYjcYaAl5xlpHD5gYizDRHE129jN2YS5GalILe9pZE/E5oYWayGf/XjEVdgF1WBxEa7L4Onw2dJ+sgmSAazOz4y6Q5NDG3C4v8Hd6NHbbEoNSJrJ8BgiqjcnXVe8k8BwrhtTXdK1uiFk3iKYfTmbhBMqWYBh+UBFDnBiarf7cSpub+5BE6V7lFq8YOZsbTTYJ3zunxJ7SI6c90ZwarE6/5HJVqo6aoz1N941/wNQuPpTYHl/rEuG3vFmPDnm/NiSKSL1VWGOoonKxgVgIWEEaR3ggpWkudf8nTzxgzziaFGPAe6+y+bPb+qsIlUuk7Q46T8mu0QFZhXlAz0ZhtLs03cXggNx2wrI1nNdWRcN6vDy0WSmNAUaymjoZF5p/3EQl/l0=
  app: lets-goal
  on:
    repo: dngiang/lets-goal
